defaults:
  - env/train: libero_object
  - env/eval: libero_object
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null
  searchpath:
    - file://${oc.env:EMBODIED_PATH}/config/

cluster:
  num_nodes: 1
  num_gpus_per_node: 8
  component_placement:
    actor: 0-7
    env: 0-7
    rollout: 0-7

runner:
  task_type: embodied
  logger:
    log_path: "./logs"
    tensorboard:
      enable: True
      queue_size: 10
    wandb:
      enable: False
      project_name: "infini-rl"
      experiment_name: "test_pi0"

  max_epochs: 1000
  max_steps: -1

  val_check_interval: 5
  save_interval: 1000
  seq_length: 4096
  max_prompt_length: 50

algorithm:
  auto_reset: False
  ignore_terminations: False
  use_fixed_reset_state_ids: True
  require_values: False
  shuffle_samples: True
  normalize_advantages: False
  kl_penalty: kl  # how to estimate kl divergence: kl or kl_penalty
  group_size: 1
  n_chunk_steps: 48
  n_eval_chunk_steps: 48
  # training generation mbs
  rollout_micro_batch_size: 64
  num_group_envs: 64
  rollout_epoch: 8
  reward_type: chunk_level
  logprob_type: "chunk_level"
  entropy_type: "token_level"

  # mbs to do log prob inference, can be set to
  # lower than rollout_micro_batch_size to reduce
  # memory usage
  logprob_forward_micro_batch_size: 16
  adv_type: "embodied_gae"
  loss_type: "embodied_ppo" # specifically for pi0
  loss_agg_func: "token-mean" 
  kl_beta: 0.0
  ratio_clip_eps: 0.2
  entropy_bonus: 0.001
  clip_ratio_high: 0.2
  clip_ratio_low: 0.2
  value_clip: 0.2
  huber_delta: 10.0
  clip_ratio_c: 3.0
  gamma: 0.99
  gae_lambda: 0.95
  use_norm_adv: True
  filter_rewards: False
  rewards_lower_bound: 0.1
  rewards_upper_bound: 0.9
  # params for generation
  sampling_params:
    use_greedy: False
    temperature_train: 1.0
    temperature_eval: 0.6
    top_k: 50
    top_p: 1.0
    repetition_penalty: 1.0
    add_BOS: False

  # length argument for autoregressive sampling
  # max length means max amount of tokens to generate
  length_params:
    max_new_token: null
    max_length: 1024
    min_length: 1

env:
  group_name: "EnvGroup"
  channel:
    name: "env_buffer_list"
    queue_name: "obs_buffer"
    queue_size: 0
  enable_offload: False

rollout:
  group_name: "GenerationGroup"
  channel:
    name: ${env.channel.name}
    queue_name: "action_buffer"
    queue_size: 0
  mode: "colocate"
  generation_backend: "huggingface"
  model_dir: "/mnt/mnt/public/chenkang/openpi-main/checkpoints/sft/pi0_libero/all_patch_3/30000"
  recompute_logprobs: False
  unnorm_key: libero_10
  enable_offload: False
  pipeline_stage_num: 1

data:
  type: "simulator"
  simulator_type: "cpu"

actor:
  group_name: "TrainerGroup"
  channel:
    name: ${env.channel.name}
    queue_name: "replay_buffer"
    queue_size: 0
  training_backend: "fsdp"
  checkpoint_load_path: "/mnt/mnt/public/chenkang/openpi-main/checkpoints/sft/pi0_libero/all_patch_3/30000"
  checkpoint_save_path: "/mnt/mnt/public/liuzhihao/result"
  micro_batch_size: 64
  global_batch_size: 1024 # maximun : global batch size = micro batch size * actor num_processes.
  seed: 42
  enable_offload: False
  load_data_for_test: False

  model:
    model_name: "openpi"
    precision: null
    num_action_chunks: 5 # interface for the env
    action_dim: 7
    is_lora: False
    num_images_in_input: 2
    use_proprio: True
    num_steps: 3
    sharding_strategy: "no_shard"
    # openpi specific parameters
    openpi:
      noise_level: 0.5
      action_chunk: ${actor.model.num_action_chunks}
      num_steps: ${actor.model.num_steps}
      train_expert_only: True
      action_env_dim: ${actor.model.action_dim}
      noise_method: "flow_sde" 
      adv_method: ppo
    

  optim:
    lr: 1.0e-6
    value_lr: 1.0e-4
    adam_beta1: 0.9
    adam_beta2: 0.95
    adam_eps: 1.0e-05
    clip_grad: 0.6

  tokenizer:
    tokenizer_type: "HuggingFaceTokenizer"
    # TODO: Update to PI0 model path when available
    tokenizer_model: "/mnt/mnt/public/liuzhihao/libero_sft_model_all/sft/libero_spatial_lerobot/few_1/checkpoints/030000/pretrained_model"
    # /mnt/mnt/public/liuzhihao/megatron-infinigence-rl-chenk/pretrained_model/
    extra_vocab_size: 421
    use_fast: False
    trust_remote_code: True
    padding_side: "right"

reward:
  use_reward_model: False

critic:
  use_critic_model: False
