simulator_type: libero
task_suite_name: libero_object

auto_reset: False
ignore_terminations: False
max_episode_steps: 240

use_rel_reward: True
reward_coef: 1.0
only_eval: True

seed: 0
num_group: ${env.eval.num_envs}
group_size: 1
use_fixed_reset_state_ids: True
use_wrist_image: ${actor.model.use_wrist_image}

num_envs: 496
video_cfg:
  save_video: True
  info_on_video: True
  video_base_dir: ${runner.logger.log_path}/video/eval

init_params:
  camera_heights: 256
  camera_widths: 256